<?php include("includes/header.php"); ?>
		<?php include("includes/menu.php"); ?>
		<div class="small-12 medium-8 align-center setting">
		    <div class="home-body-container">
		      <div class="row">
		        <div class="medium-12 columns">
		          	<div class="setting-title">
		          		Terms of Use
		          	</div>
		        </div>
		      </div>        
		      <div class="row">
		        <div class="medium-12 columns">
		        	<div class="full-text">
						<p>Please read these terms and conditions (“Terms”) before using this site. By continuing to access or use this site, or any service on this site (collectively, “SRX”), you signify your acceptance of these Terms. Streetsine (Pte. Ltd.) (“Streetsine”) reserves the right to amend, remove or add to these Terms at any time by posting new terms and conditions on this page. Such modifications shall be effective immediately and shall apply to any information you provide, or your use of any Service, after such modification. Accordingly, please continue to review these Terms whenever accessing or using SRX. Your use of SRX after the posting of modifications to these Terms will constitute your acceptance of the terms and conditions, as modified.</p>
						<p>By using SRX, you also agree to the terms of our Privacy Policy, which is incorporated by reference.</p>
						<ol>
						   <li>Access to SRX. We reserve the right to restrict access to some parts of the SRX to SRX members or certain categories of SRX members.</li>
						   <li>Data. SRX collects and collates publicly and exclusively available information from sources that include user input, real estate professionals including our SRX members, retail businesses and government agencies that include URA Realis, SingStat, SingPost and the Singapore Land Authority. SRX does not alter or manipulate the accuracy of that data when it conducts analysis or presents information in the provision of its services. To the best of our knowledge, the raw data and analytical output are accurate, but no decision should be made solely on these numbers. Property investments are subject to risks, including possible loss of principal amount invested. The value of properties may fall or rise. Past performance or any prediction or forecast is not necessarily indicative of future performance. Services rendered and information provided by SRX do not constitute and shall not be construed as constituting investment advice or recommendations and are prepared without regard to the specific objectives, financial situations or needs of any particular person who may receive or use SRX or the services provided by SRX. Investors should study all relevant information and consider whether the investment is appropriate for them. You should seek the advice of your financial, property, and legal advisors before purchasing, renting, or selling property. If you are using information from SRX to make decisions regarding the purchase, rental or sale of any property, you should thoroughly consider all your options or alternatives. Your purchase and investment decisions are solely your responsibility.</li>
						   <li>Software. SRX may include software for use in connection with the services offered on SRX. If such software is accompanied by an end user license agreement ("EULA"), the terms of the EULA will govern your use of the software. If such software is not accompanied by a EULA, then StreetSine grants you a non- exclusive, revocable, personal, non-transferable license to use such software solely in connection with the Services and in accordance with these Terms. Such licence may be terminated at anytime by StreetSine at its sole discretion. For the avoidance of doubt, the existence of a EULA in respect of any software that may be included for use in connection with the Services shall be sufficient for the terms of such EULA to govern your use of the software in connection with the Services.</li>
						   <li>Prescribed Estate Agency Agreements. The AgentConnect electronic forms have been prepared on the basis of the prescribed estate agency agreements set out in the Third Schedule of the Estate Agents Act 2010 and with regulations and guidelines set by the CEA. SRX have used reasonable efforts to ensure that electronic forms correspond with such prescribed estate agency agreements although appropriate adjustments have been made to the electronic forms so that they are optimised for electronic use.</li>
						   <li>User Content Posted on the Site. As a user of SRX, you are solely responsible for the photos, information, listings and other content that you upload, publish or display (hereinafter, "post") on or through SRX, or transmit to or share with other users (collectively the "User Content"). You may not post, transmit, or share User Content on SRX that you did not create or that you do not have permission to post. You understand and agree that StreetSine may, but is not obligated to, review SRX and may delete or remove (without notice) any Site Content or User Content in its sole discretion. You are solely responsible at your sole cost and expense for creating backup copies and replacing any User Content you post or store on SRX. </li>
						   <li>
						      When you post User Content on SRX, you authorize and direct us to make such copies thereof as we deem necessary in order to facilitate the posting and storage of the User Content on SRX. By posting User Content to any part of SRX, you are deemed to have automatically granted with consent, and you represent and warrant that you have the right to grant, to the Company an irrevocable, perpetual, non-exclusive, transferable, fully paid, worldwide license (with the right to sublicense) to use, copy, publicly perform, publicly display, reformat, translate, excerpt (in whole or in part) and distribute such User Content for any purpose, commercial, advertising, or otherwise, on or in connection with SRX or the promotion thereof, to prepare derivative works of, or incorporate into other works, such User Content, and to grant and authorize sublicenses of the foregoing. You may remove your User Content from SRX at any time. If you choose to remove your User Content, you acknowledge that StreetSine may retain archived copies of your User Content. StreetSine does not assert any ownership over your User Content; rather, as between us and you, subject to the rights granted to us in these Terms, you retain full ownership of all of your User Content and any intellectual property rights or other proprietary rights associated with your User Content.
						      <br>
						      In addition, you agree not to use SRX:
						      <ul>
						         <li>to harvest or collect email addresses or other contact information of other users from SRX by electronic or other means for the purposes of sending unsolicited emails or other unsolicited communications;</li>
						         <li>in any unlawful manner or in any other manner that could damage, disable, overburden or impair SRX;</li>
						         <li>to upload, post, transmit, share, store or otherwise make available any content that we deem to be harmful, threatening, unlawful, defamatory, infringing, abusive, inflammatory, harassing, vulgar, obscene, fraudulent, invasive of privacy or publicity rights, hateful, or racially, ethnically or otherwise objectionable;</li>
						         <li>to impersonate any person or entity, or falsely state or otherwise misrepresent yourself, your age or your affiliation with any person or entity;</li>
						         <li>to upload, post, transmit, share or otherwise make available any unsolicited or unauthorized advertising, solicitations, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation, whether or not the same contravenes any applicable law or regulation; </li>
						         <li>to upload, post, transmit, share, store or otherwise make publicly available on SRX any private information of any third party, including, addresses, phone numbers, email addresses, identity numbers and credit card numbers; </li>
						         <li>to solicit personal information from anyone under 18 or solicit passwords or personally identifying information for commercial or unlawful purposes; </li>
						         <li>to upload, post, transmit, share or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; </li>
						         <li>to upload, post, transmit, share, store or otherwise make available content that would constitute, encourage or provide instructions for a criminal offense, violate the rights of any party, or that would otherwise create liability or violate any local, state, national or international law; </li>
						         <li>to use or attempt to use another's account, service or system without authorization from SRX, or create a false identity on SRX; or </li>
						         <li>to upload, post, transmit, share, store or otherwise make available content that, in the sole judgment of StreetSine, is objectionable or which restricts or inhibits any other person from using or enjoying SRX, or which, in the sole judgment of Streetsine, may expose StreetSine, SRX or its users to any harm or liability of any type.</li>
						      </ul>
						   </li>
						   <li>Linked Materials. SRX may from time to time include links to third-party products, services and websites. StreetSine does not endorse, and takes no responsibility for such products, services, and websites. </li>
						   <li>Intellectual Property. SRX is the property of Streetsine and is subject to the intellectual property rights of Streetsine and its licensors. You acknowledge that SRX has been developed, compiled, prepared, revised, selected and arranged by Streetsine and others through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort and money and constitutes valuable intellectual property and trade secrets of Streetsine and others. All present and future right in and to trade secrets, patents, copyrights, trademarks, service marks, know-how and other proprietary rights of any type under the laws of any governmental authority shall, at all times be and remain the sole and exclusive property of Streetsine and/or its licensors and affiliates. All present and future rights in and title to SRX (including the right to exploit SRX and any portions of SRX) are reserved exclusively to Streetsine and/or its licensors and affiliates. </li>
						   <li>No Warranties. You agree that your use of SRX is at your sole risk and acknowledge that SRX and anything contained on SRX, including but not limited to, any content, services, data, information or advertisements are provided on "AS IS" and "AS AVAILABLE" and Streetsine makes no warranty of any kind, express or implied, as to any such content, services, data, information or advertisements including but not limited to, merchantability, non-infringement, title or fitness for any particular purpose or use. A substantial portion of the content, data and information available on SRX are contributed by third parties and Streetsine has no obligation to verify the accuracy or veracity of such content, data and information. Streetsine does not warrant that SRX is compatible with your equipment or that it is free of errors or viruses, worms or "Trojan horses" or any other harmful, invasive or corrupted files, and is not liable for any damage you may suffer as a result of such destructive features. Streetsine also makes no warranty in respect of the reliability or continued availability of the services on SRX. </li>
						   <li>You agree that Streetsine, its officers and employees, partners, affiliates, subsidiaries, successors and assigns shall have no responsibility or liability for: (a) any injury or damages, whether caused by the negligence of Streetsine, its officers and employees, partners, affiliates, subsidiaries, successors and assigns arising in connection with SRX and its services; (b) any fault, inaccuracy, omission, delay or any other failure in SRX caused by your equipment or arising from your use of SRX on such equipment. </li>
						   <li>Disclaimer. You acknowledge that: (a) SRX is provided for informational purposes only and is not intended to be used for trading or advisory purposes and Streetsine does not act as financial, legal or other professional advisor; (b) SRX includes information compiled from various sources, which include information that is publicly available and information that may only be exclusively available to SRX; (c) Streetsine does not guarantee the sequence, accuracy, completeness or timeliness of the services on SRX; and (d) the provision of certain parts of the services on SRX is subject to the terms and conditions of other agreements to which Streetsine is a party. Accordingly, notwithstanding anything to the contrary in these Terms, Streetsine, its officers and employees, partners, affiliates, subsidiaries, successors and assigns shall not, directly or indirectly, be liable to you, or to any person, in any way for any (i) inaccuracies or errors in or omissions from any service on SRX including but not limited to, price information, quotes and data; (ii) delays, errors or interruptions in the transmission or delivery of any service on SRX; or (iii) loss or damage arising therefrom or occasioned thereby, or by any reason of nonperformance. </li>
						   <li>LIABILITY LIMITATION; EXCLUSIVE REMEDY. TO THE FULLEST EXTENT PERMITTED BY LAW IN NO EVENT WILL STREETSINE, ITS OFFICERS AND EMPLOYEES, SHAREHOLDERS, AFFILIATES, SUBSIDIARIES, SUCCESSORS AND ASSIGNS BE LIABLE TO ANY PARTY OR PERSON FOR ANY DAMAGES OR COSTS, INCLUDING WITHOUT LIMITATION ANY INDIRECT, CONSEQUENTIAL, SPECIAL, INCIDENTAL, OR PUNITIVE DAMAGES ARISING OUT OF, BASED ON, OR RESULTING FROM THESE TERMS OR YOUR USE OF SRX OR ANY SERVICE ON SRX, EVEN IF SUCH PARTY OR PERSON HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THESE LIMITATIONS AND EXCLUSIONS APPLY WITHOUT REGARD TO WHETHER ANY DAMAGES OR COSTS ARISE FROM (A) BREACH OF CONTRACT, (B) BREACH OF WARRANTY, (C) NEGLIGENCE, (D) TORT OR (E) ANY OTHER CAUSE OF ACTION, TO THE EXTENT SUCH EXCLUSION AND LIMITATIONS ARE NOT PROHIBITED BY APPLICABLE LAW. IF YOU DO NOT AGREE WITH ANY PART OF THESE TERMS, OR YOU HAVE ANY DISPUTE OR CLAIM AGAINST STREETSINE, ITS OFFICERS AND EMPLOYEES, SHAREHOLDERS, AFFILIATES, SUBSIDIARIES, SUCCESSORS AND ASSIGNS WITH RESPECT TO THESE TERMS OR SRX, THEN YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE ACCESSING SRX OR USING ANY SERVICE ON SRX. </li>
						   <li>Indemnity. You agree to indemnify and hold StreetSine, its officers and employees, shareholders, affiliates, subsidiaries, successors and assigns harmless from and against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorney's fees, arising out of or in connection with any User Content, any third party applications, software or content you post or share on or through SRX, your use of SRX, your conduct in connection with SRX or with other users of SRX, or any violation of these Terms or of any law or the rights of any third party, including without limitation any action(s) or claims(s) against StreetSine on account of any User Content, third party applications, software or content posted or shared by you on SRX being or containing material that infringes the intellectual property of a third party. </li>
						   <li>Real Estate Licenses. StreetSine does not broker real estate transactions or act as a real estate agent for you or any other user. Before participating in a real estate transaction, we encourage you to seek the advice of your financial, property, and legal advisors. </li>
						   <li>Choice of Law; Disputes. These Terms are governed by the laws of Singapore, without giving effect to its conflict of laws provisions. You agree to submit to exclusive jurisdiction of the Singapore courts for any and all disputes, claims and actions arising from or in connection with SRX and/or these Terms. In any dispute arising under this Agreement, the prevailing party will be entitled to claim, upon satisfactory proof of the same, reasonable attorneys' fees and expenses.</li>
						   <li>Miscellaneous. If any part of these Terms are determined to be invalid or unenforceable, then the invalid or unenforceable provision will be enforced to the maximum extent permissible and the remainder of these Terms will continue in effect. The section headings in these Terms are solely used for the convenience of the parties and have no legal or contractual significance. StreetSine may assign these Terms, in whole or in part, at any time with or without notice to you. You may not assign these Terms, or assign, transfer or sublicense your rights, if any, in relation to SRX. StreetSine's failure to act with respect to a breach by you or others does not waive its right to act with respect to subsequent or similar breaches. Except as expressly stated herein, these Terms constitute the entire agreement between you and StreetSine with respect to SRX and supersede all prior or contemporaneous communications of any kind between you and StreetSine with respect thereto. </li>
						</ol>
					</div>
		        </div>
		      </div>  
		      
		    </div>

  		</div>
</body><!--body-->
<?php include("includes/footer.php"); ?>
<?php include("includes/scripts.php"); ?>